---
- name: Install Required Packages
  apt:
    name:
      - lxd
    state: present
    update_cache: yes
  tags:
    - packages
    - setup

- name: Install Local packages
  apt:
    name:
      - python-pexpect
    state: present
  become: true
  delegate_to: localhost
  when: inventory_hostname is not localhost